# Global configurations served by Spring Cloud Config Server to all microservices
spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  mail:
    host: ${MAIL_HOST:smtp.resend.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:resend}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: ${JWT_SECRET_KEY:WVhSdGFXNHRkSEpoYmkxMmFYQXRjSEp2TFdWc2FYUmxMV1JsZG1Wc2IzQmxjaTFpWVdOclpXNWtMVEpyTmc9PQ==}
  access-expiration: 900000
  refresh-expiration: 604800000

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}

PAYOS_CLIENT_ID: ${PAYOS_CLIENT_ID:}
PAYOS_API_KEY: ${PAYOS_API_KEY:}
PAYOS_CHECKSUM_KEY: ${PAYOS_CHECKSUM_KEY:}

google:
  client-id: ${GOOGLE_CLIENT_ID:}

mail:
  from: ${MAIL_FROM:atmin@atmin.io.vn}

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}
