spring.application.name=server
app.frontend.url=${FRONTEND_URL:http://localhost:5173}

spring.datasource.url=jdbc:mysql://localhost:3306/holiday_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.web.error.include-stacktrace=never
spring.data.web.pageable.serialization-mode=via-dto

jwt.secret-key=${JWT_SECRET_KEY}
jwt.access-expiration=900000
jwt.refresh-expiration=604800000

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:resend}
spring.mail.from=${MAIL_FROM:cskh@atmin.io.vn}
spring.mail.from-name=Holiday Fashion
spring.mail.password=${MAIL_PASSWORD:your_app_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Redis configurations
spring.data.redis.host=localhost
spring.data.redis.port=6379

# payos
PAYOS_CLIENT_ID=${PAYOS_CLIENT_ID:37ef7825-5fcf-4ebb-80d1-563e1b85a51f}
PAYOS_API_KEY=${PAYOS_API_KEY:64f9877c-3fcf-4ee4-9d30-f5f28446b29a}
PAYOS_CHECKSUM_KEY=${PAYOS_CHECKSUM_KEY:8d2084fc00bef53ab3a5a6a37f6fa54a40f27548ed522509378b6da48fd26b76}

# Tắt bớt log rác lúc chạy
spring.main.banner-mode=off
logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN
logging.level.org.springframework.security=WARN
logging.level.org.springframework.data=WARN