rootProject.name = 'holiday-microservices'

include 'common-library'
include 'eureka-server'
include 'config-server'
include 'api-gateway'
include 'identity-service'
include 'product-service'
include 'order-service'
include 'payment-service'
include 'promotion-service'
include 'notification-service'
include 'chat-service'
include 'media-service'
